pizzas/urls.py
from django.urls import path 
from . import views 

app_name = 'pizzas'

urlpatterns = [
    path('', views.index, name='index'),
    path('pizzas', views.pizzas, name='pizzas'),
    path('pizzas/<int:pizza_id>/', views.pizza, name='pizza'),
    path('comments/<int:pizza_id>/', views.comments, name='comments'),
]

pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
]

pizzas/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Pizza(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.TextField()

    def __str__(self):
        return self.name

class Comment(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text[:50]


    

pizzas/forms.py
from django import forms 
from .models import Pizza, Topping, Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        label =  {'Text: ': ''}
        widgets = {'text':forms.Textarea(attrs={'cols':80})}

pizzas/views.py
from django.shortcuts import render, redirect
from .models import Pizza, Topping, Comment
from .forms import CommentForm

# Create your views here.

def index(request):
    return render(request, 'pizzas/index.html')

def pizzas(request):
    pizzas = Pizza.objects.order_by('name')
    context = {'pizzas': pizzas}
    return render(request, 'pizzas/pizzas.html', context)

def pizza(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by('pizza')
    comments=pizza.comment_set.order_by('date_added')

    context = {'pizza': pizza, 'toppings': toppings, 'comments': comments}
    return render(request, 'pizzas/pizza.html', context)
    

def comments(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
        
    if request.method != 'POST':
        form = CommentForm()
    else:
        form = CommentForm(data=request.POST)
        if form.is_valid():
            comments = form.save(commit=False)
            comments.pizza = pizza
            comments.save()
            return redirect('pizzas:pizza', pizza_id=pizza_id)

    context = {'form': form, 'pizza': pizza}
    return render(request, 'pizzas/comments.html', context)

pizzas/templates/pizzas/base.html
<p>

    <body style="background-color: rgb(180, 180, 180);"> </body>

    <font face="Optima" size="5px" color="D35D0E"> Parker's Perfect Pizzeria </font><br /><br />

    <a href="{% url 'pizzas:index' %}"> Home Page
    </a>
    <br /><br />

    <a href="{% url 'pizzas:pizzas' %}"> Perfect Pizzas
    </a>



</p>

{% block content %}
{% endblock content %}

pizzas/templates/pizzas/comments.html
{% extends "pizzas/base.html" %}

{% block content %}

<p> <a href="{% url 'pizzas:pizza' pizza.id %}"> {{pizza}}</a></p>

<p> Add a Comment </p>

<form action="{% url 'pizzas:comments' pizza.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit"> Add Comment </button>
</form>

{% endblock content %}

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block content %}


<p>
    <font face="Optima" size="5px" color="D35D0E"> Welcome to Parker's perfect Pizzeria, Or 3p's for short. Here at 3p's
        we value perfection so you
        have the ability to enjoy delicious pizzas for a greate price. </font>
</p>
<p>
    <font face="Optima" size="5px" color="D35D0E"> 3p's couragous history: </font>
</p>
<p>
    <font face="Optima" size="3px" color="D35D0E"> 3p's was founded May 2, 2021, when Professor Bhojwani assigned a
        website for the python final. After many days of struggling and countless hours of hard work, our founder Parker
        Bryant was able to get the website up and running. </font>
</p>
<img src="static/pizzas/images/MeatLoversPizza.png">
{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}

{% block content %}

<p> Pizza: {{ pizza }} </p>
<p> Toppings: </p>
<ul>
    {% for topping in toppings %}

    <li>
        <p>{{ topping.name | linebreaks }}</p>
    </li>

    {% empty %}

    <li> There are no toppings on this pizza. </li>
    {% endfor %}
</ul>

<p> Comments: </p>

<ul>
    {% for c in comments %}

    <li>
        <p>{{ c.text | linebreaks }}</p>
    </li>

    {% empty %}

    <li> There are no comments on this pizza. </li>
    {% endfor %}
</ul>
<p> <a href="{% url 'pizzas:comments' pizza.id %}"> Add a Comment </a></p>

{% endblock content %}

pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block content %}
<font face="Optima" size="5px" color="D35D0E"> 3p's awsome selecton of epicly dedicious pizzas </font>

<ul>
    {% for p in pizzas %}

    <li>
        <a href="{% url 'pizzas:pizza' p.id %}"> {{ p }} </a>

    </li>
    {% empty %}
    <li>
        No pizzas have been added yet.
    </li>

    {% endfor %}
</ul>
<img src="static/pizzas/images/HawaiianPizza.png">
{% endblock content %}